### ISSUE TITLE
Get the noise output

### ISSUE THREAD

**Issue by RenieWell** [YingHuan-Chen/Time-Reversal#1]
Thanks for sharing this project!
When I ran the main.py, the code ran without any errors. But I got the wired output:
![image](https://github.com/user-attachments/assets/300cd3ae-936c-4a6f-8616-4d26edbb0c04)
It looks like the denoise did not happened.
And the local model weight has been tested, which works fine.
Can you help out?

**Comment by YingHuan-Chen** [comment]
Could you please let me know which scheduler you are using?

**Comment by RenieWell** [comment]
> Could you please let me know which scheduler you are using?

Thanks for reply, I use the same scheduler as you: EulerDiscreteScheduler. Since EulerDiscreteScheduler is used in `class TimeReversalPipeline`.

And the noise output problem was fixed after I reinstall diffuser with `pip install diffusers["torch"]==0.29.2` . However, I still got the blurring result:
![image](https://github.com/user-attachments/assets/b1255a8c-3138-41f5-ae59-9d77e71cf86f)
I am not sure if this problem came from the wrong version of diffusers or pytorch. Can you please kindly share the CUDA, Pytorch, and Diffusers' version? Did you get the same blurring result?

**Comment by YingHuan-Chen** [comment]
https://github.com/user-attachments/assets/eebf1ae7-c35e-4f03-995d-8e36134f0780
Thank you for reaching out and for your interest in my Repo. 
Here are the versions of the tools I used:
torch                      2.3.1
diffusers                0.29.2

The results attached were achieved using my default parameters.
